Repository ANrajin/ngWind, pull requests merged in 2023-12, with the labels that each got.

#16 #15- 🎉update version angular 16 to 17
  angular.json
  package-lock.json
  package.json
  src/app/admin/layouts/header/header.component.html
  src/app/admin/views/dashboard/dashboard.component.html
  src/app/admin/views/events/events.component.html
  src/app/admin/views/events/events.component.ts
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#18 #5 - 🎨 Design a landing page
  src/app/admin/layouts/header/header.component.html
  src/app/admin/layouts/header/header.component.ts
  src/app/app-routing.module.ts
  src/app/public/auth/signin/signin.component.html
  src/app/public/auth/signin/signin.component.ts
  src/app/public/auth/signup/signup.component.html
  src/app/public/auth/signup/signup.component.ts
  src/app/public/home/home.component.html
  src/app/public/layouts/footer/footer.component.css
  src/app/public/layouts/footer/footer.component.html
  src/app/public/layouts/footer/footer.component.ts
  src/app/public/layouts/header/header.component.css
  src/app/public/layouts/header/header.component.html
  src/app/public/layouts/header/header.component.ts
  src/app/public/public-routing.module.ts
  src/app/public/public.component.html
  src/app/public/public.module.ts
  src/app/public/public.routes.ts
  src/assets/data/images.ts
  src/assets/images/authpage/profile-image.jpg
  src/assets/images/authpage/signup.jpg
  src/assets/images/authpage/singupTwo.png
  src/assets/images/logo/login.png
  src/assets/images/logo/my-logo.png
  src/styles.css
  tailwind.config.js
Labels: enhancement

#21 ✨ Design tab component for admin dashboard
  package-lock.json
  package.json
  src/app/admin/admin-routing.module.ts
  src/app/admin/admin.module.ts
  src/app/admin/admin.routes.ts
  src/app/admin/layouts/sidebar/sidebar.component.html
  src/app/admin/views/elements/elements.module.ts
  src/app/admin/views/elements/modal/admin-modal.component.css
  src/app/admin/views/elements/modal/admin-modal.component.html
  src/app/admin/views/elements/modal/admin-modal.component.ts
  src/app/admin/views/elements/tab/admin-tab.component.css
  src/app/admin/views/elements/tab/admin-tab.component.html
  src/app/admin/views/elements/tab/admin-tab.component.ts
  src/app/admin/views/elements/tab/tab-items.ts
  src/app/shared/components/tab/app-nav.module.ts
  src/app/shared/components/tab/directives/tab-content.directive.ts
  src/app/shared/components/tab/directives/tab-item.directive.ts
  src/app/shared/components/tab/directives/tab-link.directive.ts
  src/app/shared/components/tab/directives/tab.directive.ts
  src/app/shared/components/tab/nav-content.directive.ts
  src/app/shared/components/tab/nav-items.directive.ts
  src/app/shared/components/tab/nav-link.directive.ts
  src/app/shared/components/tab/nav.directive.ts
  src/app/shared/components/tab/tab-contents.type.ts
  src/app/shared/components/tab/tab.component.css
  src/app/shared/components/tab/tab.component.html
  src/app/shared/components/tab/tab.component.ts
  src/app/shared/components/tab/tab.module.ts
  src/index.html
Labels: enhancement, UI Design

#22 #19 - 🎨 Design button component
  src/app/admin/admin-routing.module.ts
  src/app/admin/admin.routes.ts
  src/app/admin/layouts/sidebar/sidebar.component.html
  src/app/admin/views/elements/buttons/buttons.component.css
  src/app/admin/views/elements/buttons/buttons.component.html
  src/app/admin/views/elements/buttons/buttons.component.ts
  src/app/public/auth/signin/signin.component.html
  src/app/public/auth/signup/signup.component.html
  src/app/shared/components/button/button.module.ts
  src/app/shared/components/button/directives/app-btn-blue.directive.ts
  src/styles.css
Labels: enhancement

#27 🐞fixed admin header (z-index) and change name (Hylos to ngwind)
  angular.json
  package-lock.json
  package.json
  src/app/_core/strategies/AppTitleStrategy.ts
  src/app/admin/layouts/header/header.component.css
  src/app/admin/layouts/sidebar/sidebar.component.html
  src/app/public/layouts/footer/footer.component.html
  src/index.html
Labels: bug, enhancement
